# Generated by Django 5.2.6 on 2025-09-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
