# Generated by Django 5.2.6 on 2025-09-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0003_dailyactivity_manualentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='distance',
            field=models.FloatField(),
        ),
    ]
