# Generated by Django 5.2.6 on 2025-09-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0004_alter_dailyactivity_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualentry',
            name='distance',
        ),
    ]
