# Generated by Django 5.2.6 on 2025-09-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0005_remove_manualentry_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='manualentry',
            old_name='user',
            new_name='username',
        ),
    ]
