# Generated by Django 5.2.6 on 2025-09-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0006_rename_user_dailyactivity_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='manualentry',
            old_name='username',
            new_name='user',
        ),
    ]
