# Generated by Django 5.2.6 on 2025-10-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0008_user_auth_token_alter_user_age_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
    ]
